name: flutter_boilerplate
description: Flutter boilerplate to start any project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.5
  dio: ^5.4.0
  retrofit: ^4.1.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  dartz: ^0.10.1
  internet_connection_checker: ^1.0.0+1
  go_router: ^13.0.0
  intl: ^0.20.2
  supabase_flutter: ^2.1.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.2
  retrofit_generator: ^8.1.0
  freezed: ^2.4.7
  riverpod_generator: ^2.3.11
  riverpod_lint: ^2.3.10
  mockito: ^5.4.4
  very_good_analysis: ^9.0.0

flutter:
  generate: true
  uses-material-design: true
